geekshom_template/geekshop/basket/urls.py
from django.urls import path

from basket.views import basket_add,basket_remove,basket_edit

app_name = 'basket'
urlpatterns = [
    path('add/<int:id>/',basket_add,name='basket_add'),
    path('remove/<int:basket_id>',basket_remove,name='basket_remove'),
    path('edit/<int:basket_id>/<int:quantity>/', basket_edit,name='basket_edit')

]

geekshom_template/geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import index, products

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls',namespace='mainapp')),
    path('authapp/', include('authapp.urls',namespace='authapp')),
    path('basket/', include('basket.urls',namespace='basket')),
    path('adminapp/', include('adminapp.urls',namespace='adminapp')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

geekshom_template/geekshop/mainapp/urls.py
from django.urls import path
from mainapp.views import products, ProductDetail

app_name = 'mainapp'
urlpatterns = [
    path('',products,name='products'),
    path('detail/<int:pk>/',ProductDetail.as_view(),name='detail'),
    path('category/<int:id_category>',products,name='category'),
    path('page/<int:page>',products,name='page'),
]

geekshom_template/geekshop/mainapp/models.py
''' models for product and category'''

from django.db import models


# Create your models here.
class ProductCategories(models.Model):
    '''model for category'''

    name = models.CharField(max_length=64)
    descriptions = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    '''model for product'''

    name = models.CharField(max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    descriptions = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategories, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} | {self.category}'

geekshom_template/geekshop/mainapp/views.py
import os
import json

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render

# Create your views here.
from django.views.generic import DetailView

from mainapp.models import Product,ProductCategories

MODULE_DIR = os.path.dirname(__file__)

def read_file(name):
    file_path = os.path.join(MODULE_DIR, name)
    return  json.load(open(file_path, encoding='utf-8'))

def index(request):
    content = {
        'title': 'Geekshop'
    }
    return  render(request,'mainapp/index.html',content)


def products(request,id_category=None,page=1):

    if id_category:
        products_ = Product.objects.filter(category_id=id_category)
    else:
        products_ = Product.objects.all()

    pagination = Paginator(products_,per_page=2)

    try:
        product_pagination = pagination.page(page)
    except PageNotAnInteger:
        product_pagination = pagination.page(1)
    except EmptyPage:
        product_pagination = pagination.page(pagination.num_pages)
    content = {
        'title' : 'Geekshop - Каталог',
        'categories': ProductCategories.objects.all(),
        'products': product_pagination

    }


    return  render(request,'mainapp/products.html',content)


#

class ProductDetail(DetailView):
    model = Product
    template_name = 'mainapp/detail.html'

geekshom_template/geekshop/mainapp/templates/mainapp/includes/card.html
<div class="card_add_basket">
    <div class="row">
        {% for product in products %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="#">
                        <img class="card-img-top"
                             src="{{ product.image.url }}"
                             alt="">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="{% url 'mainapp:detail' product.id %}">{{ product.name }}</a>
                        </h4>
                        <h5>{{ product.price }}руб.</h5>
                        <p class="card-text">{{ product.description }}</p>
                    </div>
                    <div class="card-footer text-center">
                        {#                                <form action="{% url 'basket:basket_add' product.id%}" method="post">#}
                        {#                                    {% csrf_token  %}#}
                        {#                                      <button type="button" class="btn btn-outline-success">Отправить в корзину</button>#}
                        {#                               </form>#}
{#                        <a href="{% url 'basket:basket_add' product.id %} " class="btn btn-outline-success">Отправить в#}
{#                            корзину</a>#}
                        <button type="button" class="btn btn-outline-success" value="{{ product.id }}">
                             Отправить в корзину
                        </button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>